# Generated by Django 4.1.7 on 2023-08-29 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_news_shop_sizes_news_views_alter_news_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='shop_sizes',
        ),
    ]
